# Generated by Django 6.0 on 2025-12-21 18:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField(help_text='الطول بالسم')),
                ('weight', models.FloatField(help_text='الوزن بالكغ')),
                ('activity_level', models.FloatField(choices=[(1.2, 'خامل (عمل مكتبي، لا رياضة)'), (1.375, 'نشاط خفيف (1-3 أيام)'), (1.55, 'نشاط متوسط (3-5 أيام)'), (1.725, 'نشاط عالي (6-7 أيام)'), (1.9, 'نشاط فائق (عمل شاق)')], default=1.2)),
                ('goal', models.CharField(choices=[('lose', 'إنقاص الوزن'), ('maintain', 'الحفاظ على الوزن'), ('gain', 'زيادة الوزن'), ('muscle', 'بناء عضلات')], default='maintain', max_length=20)),
                ('daily_step_goal', models.IntegerField(default=6000)),
                ('bmi', models.FloatField(default=0.0)),
                ('daily_calorie_target', models.IntegerField(default=2000)),
                ('daily_water_target', models.FloatField(default=2.5)),
                ('weekly_activity_goal_hours', models.FloatField(default=2.5, help_text='الهدف الأسبوعي بالساعات')),
                ('enable_sleep_improvement', models.BooleanField(default=False)),
                ('target_wake_time', models.TimeField(default=datetime.time(7, 0))),
                ('target_bed_time', models.TimeField(blank=True, null=True)),
                ('recommended_sleep_hours', models.FloatField(default=8.0)),
                ('preferred_activity_type', models.CharField(choices=[('gym', 'نادي رياضي'), ('running', 'ركض'), ('home', 'تمارين منزلية')], default='home', max_length=20)),
                ('enable_activity_reminders', models.BooleanField(default=True, help_text='تفعيل تنبيهات الحركة')),
                ('activity_reminder_interval_hours', models.IntegerField(default=2, help_text='ذكرني بالحركة كل X ساعات')),
                ('enable_water_reminders', models.BooleanField(default=True, help_text='تفعيل تنبيهات شرب الماء')),
                ('water_reminder_interval_minutes', models.IntegerField(default=60, help_text='ذكرني بالشرب كل X دقيقة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
