# Generated by Django 6.0 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_burn_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="activity_level",
            field=models.FloatField(
                choices=[
                    (1.2, "خامل"),
                    (1.375, "نشاط خفيف"),
                    (1.55, "نشاط متوسط"),
                    (1.725, "نشاط عالٍ"),
                    (1.9, "نشاط مرتفع جداً"),
                ],
                default=1.2,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="activity_reminder_interval_hours",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="enable_activity_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="enable_water_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="goal",
            field=models.CharField(
                choices=[
                    ("lose", "خسارة وزن"),
                    ("maintain", "حفاظ"),
                    ("gain", "زيادة"),
                    ("muscle", "كتلة عضلية"),
                ],
                default="maintain",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(help_text="الطول بالسنتيمتر"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_activity_type",
            field=models.CharField(
                choices=[("gym", "تمارين نادي"), ("running", "جري/مشي"), ("home", "منزل")],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="water_reminder_interval_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weekly_activity_goal_hours",
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(help_text="الوزن بالكيلوغرام"),
        ),
    ]
