# Generated by Django 5.2.10 on 2026-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, 'خامل'), (1.375, 'نشاط خفيف'), (1.55, 'نشاط متوسط'), (1.725, 'نشاط عالٍ'), (1.9, 'نشاط مرتفع جدًا')], default=1.2),
        ),
    ]
