# Generated by Django 5.2.10 on 2026-07-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_avatar_url_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manual_daily_water_target',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
