# Generated by Django 5.2.12 on 2026-04-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=80)),
                ('instructions', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('severity_options', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='cholesterol_mg_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='potassium_mg_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='saturated_fat_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium_mg_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='trans_fat_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vitamin_c_mg_100g',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ConditionMedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.TimeField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.conditionmedication')),
            ],
            options={
                'ordering': ('time_of_day', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HealthRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_code', models.CharField(blank=True, max_length=50)),
                ('restriction_key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('activity', 'Activity'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('medication', 'Medication'), ('monitoring', 'Monitoring')], max_length=20)),
                ('metric_key', models.CharField(max_length=80)),
                ('evaluation_mode', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('min_required_value', models.FloatField(blank=True, null=True)),
                ('max_allowed_value', models.FloatField(blank=True, null=True)),
                ('is_forbidden', models.BooleanField(default=False)),
                ('is_scored', models.BooleanField(default=True)),
                ('guidance', models.TextField(blank=True)),
                ('evidence_source', models.CharField(blank=True, max_length=255)),
                ('is_inference', models.BooleanField(default=False)),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='core.conditiontype')),
            ],
            options={
                'ordering': ('condition_type__name', 'category', 'title'),
            },
        ),
        migrations.CreateModel(
            name='UserCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('controlled', 'Controlled'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('severity_code', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_conditions', to='core.conditiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-diagnosis_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HealthTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(max_length=80)),
                ('target_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=20)),
                ('metric_key', models.CharField(max_length=80)),
                ('evaluation_mode', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('within_target', 'Within target'), ('out_of_range', 'Out of range'), ('not_evaluated', 'Not evaluated')], default='pending', max_length=20)),
                ('is_scored', models.BooleanField(default=True)),
                ('guidance', models.TextField(blank=True)),
                ('evidence_source', models.CharField(blank=True, max_length=255)),
                ('is_inference', models.BooleanField(default=False)),
                ('last_evaluated_value', models.FloatField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('source_restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_targets', to='core.healthrestriction')),
                ('user_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='core.usercondition')),
            ],
            options={
                'ordering': ('category', 'target_name'),
            },
        ),
        migrations.CreateModel(
            name='HealthIndicatorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_records', to='core.usercondition')),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.AddField(
            model_name='conditionmedication',
            name='user_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.usercondition'),
        ),
        migrations.CreateModel(
            name='ConditionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('alert_type', models.CharField(choices=[('medication', 'Medication'), ('restriction', 'Restriction'), ('monitoring', 'Monitoring')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('seen', 'Seen'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('user_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.usercondition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConditionMedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('taken_on_time', 'Taken on time'), ('taken_late', 'Taken late'), ('missed', 'Missed'), ('skipped', 'Skipped')], max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.conditionmedicationschedule')),
            ],
            options={
                'ordering': ('-scheduled_date', '-id'),
                'unique_together': {('schedule', 'scheduled_date')},
            },
        ),
        migrations.CreateModel(
            name='ConditionDailyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('medication_adherence_percent', models.FloatField(default=0)),
                ('restriction_adherence_percent', models.FloatField(default=0)),
                ('points_delta', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_evaluations', to='core.usercondition')),
            ],
            options={
                'ordering': ('-evaluation_date', '-id'),
                'unique_together': {('user_condition', 'evaluation_date')},
            },
        ),
    ]
