# Generated by Django 5.2.12 on 2026-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_condition_rule_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionmedicationlog',
            name='status',
            field=models.CharField(choices=[('snoozed', 'Snoozed'), ('taken_on_time', 'Taken on time'), ('taken_late', 'Taken late'), ('missed', 'Missed'), ('skipped', 'Skipped')], max_length=20),
        ),
    ]
