# Generated by Django 5.2.12 on 2026-04-15 19:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_nutrition_domain(apps, schema_editor):
    FoodItem = apps.get_model("core", "FoodItem")
    MealLog = apps.get_model("core", "MealLog")
    NutritionFacts = apps.get_model("core", "NutritionFacts")
    NutritionServingOption = apps.get_model("core", "NutritionServingOption")

    for food in FoodItem.objects.all():
        food.default_serving_size = food.serving_grams or 100
        food.default_serving_unit = "g"
        food.save(update_fields=["default_serving_size", "default_serving_unit"])

        NutritionFacts.objects.get_or_create(
            food_item=food,
            defaults={
                "basis_type": "per_100g",
                "basis_value": 100,
                "serving_size": food.serving_grams or 100,
                "serving_unit": "g",
                "calories_kcal": food.calories_100g or 0,
                "protein_g": food.protein_100g or 0,
                "carbohydrates_g": food.carbs_100g or 0,
                "sugars_g": food.sugar_100g or 0,
                "fiber_g": food.fiber_100g or 0,
                "fat_g": food.fat_100g or 0,
                "saturated_fat_g": food.saturated_fat_100g or 0,
                "trans_fat_g": food.trans_fat_100g or 0,
                "cholesterol_mg": food.cholesterol_mg_100g or 0,
                "sodium_mg": food.sodium_mg_100g or 0,
                "potassium_mg": food.potassium_mg_100g or 0,
                "vitamin_c_mg": food.vitamin_c_mg_100g or 0,
                "source_name": "VitaMate legacy food catalog",
                "source_reference": f"legacy-fooditem:{food.pk}",
            },
        )
        NutritionServingOption.objects.get_or_create(
            food_item=food,
            name=food.serving_label or "Serving",
            defaults={
                "amount": 1,
                "unit": "serving",
                "grams_equivalent": food.serving_grams or 100,
                "is_default": True,
                "sort_order": 0,
            },
        )

    for log in MealLog.objects.select_related("food").all():
        food = log.food
        quantity_grams = log.quantity_grams or 0
        factor = quantity_grams / 100.0
        consumed_at = None
        if log.date:
            naive = datetime.datetime.combine(log.date, datetime.time.min)
            consumed_at = django.utils.timezone.make_aware(naive)

        log.quantity = quantity_grams
        log.unit = "g"
        log.grams_consumed = quantity_grams
        log.consumed_at = consumed_at
        log.snapshot_calories_kcal = (food.calories_100g or 0) * factor
        log.snapshot_protein_g = (food.protein_100g or 0) * factor
        log.snapshot_carbohydrates_g = (food.carbs_100g or 0) * factor
        log.snapshot_sugars_g = (food.sugar_100g or 0) * factor
        log.snapshot_fiber_g = (food.fiber_100g or 0) * factor
        log.snapshot_fat_g = (food.fat_100g or 0) * factor
        log.snapshot_saturated_fat_g = (food.saturated_fat_100g or 0) * factor
        log.snapshot_trans_fat_g = (food.trans_fat_100g or 0) * factor
        log.snapshot_cholesterol_mg = (food.cholesterol_mg_100g or 0) * factor
        log.snapshot_sodium_mg = (food.sodium_mg_100g or 0) * factor
        log.snapshot_potassium_mg = (food.potassium_mg_100g or 0) * factor
        log.snapshot_vitamin_c_mg = (food.vitamin_c_mg_100g or 0) * factor
        log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_conditionmedicationlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_type', models.CharField(choices=[('per_100g', 'Per 100g'), ('per_100ml', 'Per 100ml'), ('per_serving', 'Per serving')], default='per_100g', max_length=20)),
                ('basis_value', models.FloatField(default=100)),
                ('serving_size', models.FloatField(default=100)),
                ('serving_unit', models.CharField(default='g', max_length=20)),
                ('calories_kcal', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbohydrates_g', models.FloatField(default=0)),
                ('sugars_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('saturated_fat_g', models.FloatField(default=0)),
                ('trans_fat_g', models.FloatField(default=0)),
                ('cholesterol_mg', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('potassium_mg', models.FloatField(default=0)),
                ('calcium_mg', models.FloatField(default=0)),
                ('iron_mg', models.FloatField(default=0)),
                ('magnesium_mg', models.FloatField(default=0)),
                ('zinc_mg', models.FloatField(default=0)),
                ('phosphorus_mg', models.FloatField(default=0)),
                ('vitamin_a_mcg', models.FloatField(default=0)),
                ('vitamin_c_mg', models.FloatField(default=0)),
                ('vitamin_d_mcg', models.FloatField(default=0)),
                ('vitamin_b12_mcg', models.FloatField(default=0)),
                ('folate_mcg', models.FloatField(default=0)),
                ('monounsaturated_fat_g', models.FloatField(default=0)),
                ('polyunsaturated_fat_g', models.FloatField(default=0)),
                ('added_sugars_g', models.FloatField(default=0)),
                ('water_g', models.FloatField(default=0)),
                ('caffeine_mg', models.FloatField(default=0)),
                ('vitamin_e_mg', models.FloatField(default=0)),
                ('vitamin_k_mcg', models.FloatField(default=0)),
                ('vitamin_b1_mg', models.FloatField(default=0)),
                ('vitamin_b2_mg', models.FloatField(default=0)),
                ('vitamin_b3_mg', models.FloatField(default=0)),
                ('vitamin_b6_mg', models.FloatField(default=0)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionServingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('amount', models.FloatField(default=1)),
                ('unit', models.CharField(max_length=20)),
                ('grams_equivalent', models.FloatField(blank=True, null=True)),
                ('milliliters_equivalent', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('food_item__name', 'sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='default_serving_size',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='default_serving_unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='density_g_per_ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='item_type',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage')], default='food', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='grams_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='milliliters_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='meallog',
            name='servings_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_added_sugars_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_caffeine_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_calcium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_calories_kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_carbohydrates_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_cholesterol_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_fiber_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_folate_mcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_iron_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_magnesium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_monounsaturated_fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_phosphorus_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_polyunsaturated_fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_potassium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_protein_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_saturated_fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_sodium_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_sugars_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_trans_fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_a_mcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_b12_mcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_b1_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_b2_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_b3_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_b6_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_c_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_d_mcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_e_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_vitamin_k_mcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_water_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='snapshot_zinc_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('barcode', 'Barcode'), ('favorite', 'Favorite'), ('ai', 'AI')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='meallog',
            name='unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories_100g',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('drink', 'Drink')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('barcode__isnull', True), _negated=True), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='unique_fooditem_nonempty_barcode'),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='food_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_facts', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='nutritionservingoption',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_options', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='serving_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='core.nutritionservingoption'),
        ),
        migrations.RunPython(backfill_nutrition_domain, migrations.RunPython.noop),
    ]
