# Generated by Django 5.2.12 on 2026-04-15 20:49

import django.utils.timezone
from django.db import migrations, models


def backfill_chronic_v1_schema(apps, schema_editor):
    ConditionType = apps.get_model("core", "ConditionType")
    UserCondition = apps.get_model("core", "UserCondition")
    HealthTarget = apps.get_model("core", "HealthTarget")
    HealthIndicatorRecord = apps.get_model("core", "HealthIndicatorRecord")
    ConditionAlert = apps.get_model("core", "ConditionAlert")
    ConditionDailyEvaluation = apps.get_model("core", "ConditionDailyEvaluation")

    setup_configs = {
        "diabetes": {
            "slug": "diabetes",
            "display_name": "Diabetes",
            "sort_order": 1,
            "is_supported": True,
            "setup_schema": {
                "setup_fields": [
                    {"key": "glucose_target", "label": "Glucose target", "type": "number", "unit": "mg/dL", "required": False},
                    {"key": "hba1c_target", "label": "HbA1c target", "type": "number", "unit": "%", "required": False},
                ],
                "measurement_types": ["glucose"],
                "supports_direct_daily_reading": True,
                "profile_defaults": {"glucose_target": 130, "hba1c_target": 7.0},
            },
        },
        "hypertension": {
            "slug": "hypertension",
            "display_name": "Hypertension",
            "sort_order": 2,
            "is_supported": True,
            "setup_schema": {
                "setup_fields": [
                    {"key": "systolic_target", "label": "Systolic target", "type": "number", "unit": "mm Hg", "required": False},
                    {"key": "diastolic_target", "label": "Diastolic target", "type": "number", "unit": "mm Hg", "required": False},
                    {"key": "sodium_limit", "label": "Sodium limit", "type": "number", "unit": "mg/day", "required": False},
                ],
                "measurement_types": ["blood_pressure"],
                "supports_direct_daily_reading": True,
                "profile_defaults": {"systolic_target": 129, "diastolic_target": 79, "sodium_limit": 1500},
            },
        },
        "hyperlipidemia": {
            "slug": "dyslipidemia",
            "display_name": "Dyslipidemia",
            "sort_order": 3,
            "is_supported": True,
            "setup_schema": {
                "setup_fields": [
                    {"key": "hdl_target", "label": "HDL target", "type": "number", "unit": "mg/dL", "required": False},
                    {"key": "triglyceride_target", "label": "Triglycerides target", "type": "number", "unit": "mg/dL", "required": False},
                    {"key": "followup_interval_days", "label": "Follow-up interval", "type": "number", "unit": "days", "required": False},
                ],
                "measurement_types": ["lipid_panel"],
                "supports_direct_daily_reading": False,
                "aliases": ["hyperlipidemia"],
                "profile_defaults": {"hdl_target": 40, "triglyceride_target": 150, "followup_interval_days": 90},
            },
        },
    }

    for condition_type in ConditionType.objects.all():
        config = setup_configs.get(condition_type.code)
        if config:
            condition_type.slug = config["slug"]
            condition_type.display_name = config["display_name"]
            condition_type.is_supported = config["is_supported"]
            condition_type.sort_order = config["sort_order"]
            condition_type.setup_schema = config["setup_schema"]
        else:
            condition_type.slug = condition_type.code
            condition_type.display_name = condition_type.name
            condition_type.is_supported = False
            condition_type.sort_order = 99
            condition_type.setup_schema = {}
        condition_type.save(
            update_fields=["slug", "display_name", "is_supported", "sort_order", "setup_schema"]
        )

    for condition in UserCondition.objects.select_related("condition_type").all():
        existing = dict(condition.profile_data or {})
        defaults = {}
        code = condition.condition_type.code
        if code == "diabetes":
            defaults = {"glucose_target": 130, "hba1c_target": 7.0}
        elif code == "hypertension":
            defaults = {"systolic_target": 129, "diastolic_target": 79, "sodium_limit": 1500}
        elif code == "hyperlipidemia":
            defaults = {"hdl_target": 40, "triglyceride_target": 150, "followup_interval_days": 90}

        targets = HealthTarget.objects.filter(user_condition=condition)
        for target in targets:
            if target.target_key == "fasting_glucose" and target.max_value is not None:
                defaults["glucose_target"] = target.max_value
            elif target.target_key == "blood_pressure_systolic" and target.max_value is not None:
                defaults["systolic_target"] = target.max_value
            elif target.target_key == "blood_pressure_diastolic" and target.max_value is not None:
                defaults["diastolic_target"] = target.max_value
            elif target.target_key == "sodium_mg" and target.max_value is not None:
                defaults["sodium_limit"] = target.max_value
            elif target.target_key == "ldl_cholesterol" and target.max_value is not None:
                defaults["ldl_target"] = target.max_value

        defaults.update(existing)
        condition.profile_data = defaults
        condition.save(update_fields=["profile_data"])

    for record in HealthIndicatorRecord.objects.all():
        indicator_name = (record.indicator_name or "").strip().lower()
        record.indicator_type = indicator_name
        record.value_1 = record.value
        record.value_2 = None
        record.value_3 = None
        record.reading_context = ""
        record.payload = record.payload or {}
        if indicator_name in {"fasting_glucose", "glucose"}:
            record.indicator_type = "glucose"
            record.reading_context = "fasting"
            record.payload = {"value": record.value, "reading_type": "fasting"}
        elif indicator_name == "postprandial_glucose":
            record.indicator_type = "glucose"
            record.reading_context = "after_meal"
            record.payload = {"value": record.value, "reading_type": "after_meal"}
        elif indicator_name == "blood_pressure_systolic":
            record.indicator_type = "blood_pressure"
            record.value_2 = None
            record.payload = {"blood_pressure_systolic": record.value}
        elif indicator_name == "blood_pressure_diastolic":
            record.indicator_type = "blood_pressure"
            record.value_1 = None
            record.value_2 = record.value
            record.payload = {"blood_pressure_diastolic": record.value}
        elif indicator_name in {"ldl_cholesterol", "hdl_cholesterol", "triglycerides"}:
            record.indicator_type = "lipid_panel"
            if indicator_name == "ldl_cholesterol":
                record.value_1 = record.value
            elif indicator_name == "hdl_cholesterol":
                record.value_1 = None
                record.value_2 = record.value
            elif indicator_name == "triglycerides":
                record.value_1 = None
                record.value_3 = record.value
            record.payload = {indicator_name: record.value}
        record.save(
            update_fields=[
                "indicator_type",
                "value_1",
                "value_2",
                "value_3",
                "reading_context",
                "payload",
            ]
        )

    for alert in ConditionAlert.objects.all():
        if not alert.code:
            alert.code = alert.alert_type or "alert"
        if not alert.level:
            alert.level = "info" if alert.alert_type == "medication" else "warning"
        if alert.metadata is None:
            alert.metadata = {}
        alert.save(update_fields=["code", "level", "metadata"])

    for evaluation in ConditionDailyEvaluation.objects.select_related("user_condition").all():
        if evaluation.restriction_adherence_percent < 50:
            evaluation.status = "attention_needed"
        else:
            evaluation.status = "stable"
        latest_record = (
            HealthIndicatorRecord.objects.filter(user_condition=evaluation.user_condition)
            .order_by("-recorded_at", "-id")
            .first()
        )
        evaluation.latest_recorded_at = latest_record.recorded_at if latest_record else None
        evaluation.risk_flags = list(evaluation.risk_flags or [])
        evaluation.recommendations_payload = list(evaluation.recommendations_payload or [])
        evaluation.tracker_impacts_payload = list(evaluation.tracker_impacts_payload or [])
        evaluation.save(
            update_fields=[
                "status",
                "latest_recorded_at",
                "risk_flags",
                "recommendations_payload",
                "tracker_impacts_payload",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_nutrition_items_250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditiontype',
            options={'ordering': ('sort_order', 'display_name', 'name')},
        ),
        migrations.AddField(
            model_name='conditionalert',
            name='code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='conditionalert',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='conditionalert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conditiondailyevaluation',
            name='latest_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditiondailyevaluation',
            name='recommendations_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditiondailyevaluation',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditiondailyevaluation',
            name='status',
            field=models.CharField(choices=[('stable', 'Stable'), ('attention_needed', 'Attention needed'), ('critical', 'Critical')], default='stable', max_length=30),
        ),
        migrations.AddField(
            model_name='conditiondailyevaluation',
            name='tracker_impacts_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditiontype',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conditiontype',
            name='is_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conditiontype',
            name='setup_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conditiontype',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conditiontype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='indicator_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='reading_context',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='risk_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='value_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='value_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthindicatorrecord',
            name='value_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercondition',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='healthindicatorrecord',
            name='indicator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='healthindicatorrecord',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='healthindicatorrecord',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthtarget',
            name='source_type',
            field=models.CharField(choices=[('computed_condition_rule', 'Computed condition rule'), ('dynamic_condition_state', 'Dynamic condition state'), ('physician_override', 'Physician override'), ('user_custom', 'User custom')], default='computed_condition_rule', max_length=30),
        ),
        migrations.RunPython(backfill_chronic_v1_schema, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='conditiontype',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
