# Generated by Django 5.2.10 on 2026-04-17 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


NUTRIENT_SEEDS = [
    ("calories_kcal", "Calories", "kcal", "macro", True),
    ("protein_g", "Protein", "g", "macro", True),
    ("carbohydrates_g", "Carbohydrates", "g", "macro", True),
    ("sugars_g", "Sugars", "g", "macro", True),
    ("added_sugars_g", "Added sugars", "g", "macro", True),
    ("fiber_g", "Fiber", "g", "macro", True),
    ("fat_g", "Fat", "g", "macro", True),
    ("saturated_fat_g", "Saturated fat", "g", "macro", True),
    ("trans_fat_g", "Trans fat", "g", "macro", True),
    ("cholesterol_mg", "Cholesterol", "mg", "other", True),
    ("sodium_mg", "Sodium", "mg", "mineral", True),
    ("potassium_mg", "Potassium", "mg", "mineral", True),
    ("calcium_mg", "Calcium", "mg", "mineral", False),
    ("iron_mg", "Iron", "mg", "mineral", False),
    ("magnesium_mg", "Magnesium", "mg", "mineral", False),
    ("zinc_mg", "Zinc", "mg", "mineral", False),
    ("phosphorus_mg", "Phosphorus", "mg", "mineral", False),
    ("vitamin_a_mcg", "Vitamin A", "mcg", "vitamin", False),
    ("vitamin_c_mg", "Vitamin C", "mg", "vitamin", False),
    ("vitamin_d_mcg", "Vitamin D", "mcg", "vitamin", False),
    ("vitamin_b12_mcg", "Vitamin B12", "mcg", "vitamin", False),
    ("folate_mcg", "Folate", "mcg", "vitamin", False),
    ("vitamin_e_mg", "Vitamin E", "mg", "vitamin", False),
    ("vitamin_k_mcg", "Vitamin K", "mcg", "vitamin", False),
    ("vitamin_b1_mg", "Vitamin B1", "mg", "vitamin", False),
    ("vitamin_b2_mg", "Vitamin B2", "mg", "vitamin", False),
    ("vitamin_b3_mg", "Vitamin B3", "mg", "vitamin", False),
    ("vitamin_b6_mg", "Vitamin B6", "mg", "vitamin", False),
    ("caffeine_mg", "Caffeine", "mg", "stimulant", True),
    ("water_g", "Water", "g", "other", True),
]


def seed_nutrients_and_backfill(apps, schema_editor):
    FoodItem = apps.get_model("core", "FoodItem")
    NutritionFacts = apps.get_model("core", "NutritionFacts")
    Nutrient = apps.get_model("core", "Nutrient")
    ItemNutrientValue = apps.get_model("core", "ItemNutrientValue")
    WaterLog = apps.get_model("core", "WaterLog")

    nutrients_by_code = {}
    for code, name, unit, category, is_core in NUTRIENT_SEEDS:
        nutrient, _ = Nutrient.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "unit": unit,
                "category": category,
                "is_core": is_core,
            },
        )
        nutrients_by_code[code] = nutrient

    for facts in NutritionFacts.objects.select_related("food_item").all():
        item = facts.food_item
        basis_amount = facts.basis_amount or facts.basis_value or 100
        if facts.basis_type == "per_100ml":
            basis_unit = "ml"
        elif facts.basis_type == "per_serving":
            serving_unit = str(facts.serving_unit or "").strip().lower()
            basis_unit = serving_unit if serving_unit in {"g", "ml"} else "serving"
        else:
            basis_unit = "g"

        update_facts = []
        if facts.basis_amount != basis_amount:
            facts.basis_amount = basis_amount
            update_facts.append("basis_amount")
        if facts.basis_unit != basis_unit:
            facts.basis_unit = basis_unit
            update_facts.append("basis_unit")
        if update_facts:
            facts.save(update_fields=update_facts)

        is_drink = item.item_type in {"beverage", "drink"}
        update_item = []
        if is_drink and not item.is_hydration_trackable:
            item.is_hydration_trackable = True
            update_item.append("is_hydration_trackable")
        desired_reference_unit = "ml" if is_drink else "g"
        if item.default_reference_unit != desired_reference_unit:
            item.default_reference_unit = desired_reference_unit
            update_item.append("default_reference_unit")
        contains_caffeine = float(facts.caffeine_mg or 0) > 0
        if item.contains_caffeine != contains_caffeine:
            item.contains_caffeine = contains_caffeine
            update_item.append("contains_caffeine")
        if update_item:
            item.save(update_fields=update_item)

        for code, *_ in NUTRIENT_SEEDS:
            amount = float(getattr(facts, code, 0) or 0)
            if amount == 0:
                continue
            ItemNutrientValue.objects.update_or_create(
                item=item,
                nutrient=nutrients_by_code[code],
                basis_amount=basis_amount,
                basis_unit=basis_unit,
                defaults={"amount": amount},
            )

    WaterLog.objects.filter(drink_item__isnull=True, food_item__isnull=False).update(
        drink_item=models.F("food_item")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_old_medication_log_schedule_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('macro', 'Macro'), ('vitamin', 'Vitamin'), ('mineral', 'Mineral'), ('stimulant', 'Stimulant'), ('other', 'Other')], default='other', max_length=30)),
                ('is_core', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='contains_caffeine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='default_reference_unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_hydration_trackable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='source',
            field=models.CharField(choices=[('usda', 'USDA'), ('manual', 'Manual'), ('ai', 'AI'), ('custom', 'Custom')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='basis_amount',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='basis_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter'), ('serving', 'Serving')], default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='drink_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink_water_logs', to='core.fooditem'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_type',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('drink', 'Drink')], default='food', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemNutrientValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('basis_amount', models.FloatField(default=100)),
                ('basis_unit', models.CharField(default='g', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_values', to='core.fooditem')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_values', to='core.nutrient')),
            ],
            options={
                'ordering': ('item__name', 'nutrient__category', 'nutrient__name'),
                'constraints': [models.UniqueConstraint(fields=('item', 'nutrient', 'basis_amount', 'basis_unit'), name='unique_item_nutrient_basis')],
            },
        ),
        migrations.CreateModel(
            name='ConditionNutrientRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('max', 'Maximum'), ('min', 'Minimum'), ('avoid', 'Avoid'), ('warn', 'Warn')], max_length=20)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('threshold_unit', models.CharField(blank=True, max_length=30)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_rules', to='core.conditiontype')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_rules', to='core.nutrient')),
            ],
            options={
                'ordering': ('condition_type__code', 'severity', 'nutrient__code', 'rule_type'),
                'constraints': [models.UniqueConstraint(fields=('condition_type', 'nutrient', 'rule_type', 'severity'), name='unique_condition_nutrient_rule')],
            },
        ),
        migrations.CreateModel(
            name='UserNutrientTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('source', models.CharField(choices=[('default', 'Default'), ('condition', 'Condition'), ('manual', 'Manual')], default='default', max_length=30)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_targets', to='core.nutrient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id', 'period', 'nutrient__code', 'source'),
                'constraints': [models.UniqueConstraint(fields=('user', 'nutrient', 'period', 'source'), name='unique_user_nutrient_target')],
            },
        ),
        migrations.RunPython(seed_nutrients_and_backfill, migrations.RunPython.noop),
    ]
