# Generated by Django 5.2.10 on 2026-04-17 15:45

import django.db.models.deletion
import re
import unicodedata
from django.conf import settings
from django.db import migrations, models


CATEGORY_SEEDS = [
    ("uncategorized", "Uncategorized", 0),
    ("dessert", "Dessert", 10),
    ("pastry", "Pastry", 20),
    ("bakery", "Bakery", 30),
    ("fruit", "Fruit", 40),
    ("vegetable", "Vegetable", 50),
    ("dairy", "Dairy", 60),
    ("coffee", "Coffee", 70),
    ("tea", "Tea", 80),
    ("juice", "Juice", 90),
    ("soft_drink", "Soft drink", 100),
    ("energy_drink", "Energy drink", 110),
    ("snack", "Snack", 120),
    ("fast_food", "Fast food", 130),
    ("protein", "Protein", 140),
]

CATEGORY_KEYWORDS = [
    ("coffee", ["coffee", "espresso", "latte", "cappuccino", "mocha"]),
    ("tea", ["tea"]),
    ("juice", ["juice", "smoothie"]),
    ("energy_drink", ["energy drink", "red bull", "monster"]),
    ("soft_drink", ["soda", "cola", "soft drink", "soft_drink"]),
    ("dessert", ["dessert", "cake", "cookie", "ice cream", "chocolate", "sweet"]),
    ("pastry", ["pastry", "croissant", "donut", "danish"]),
    ("bakery", ["bakery", "bread", "toast", "bagel"]),
    ("fruit", ["fruit", "apple", "banana", "orange", "berry", "strawberry"]),
    ("vegetable", ["vegetable", "lettuce", "tomato", "cucumber", "carrot"]),
    ("dairy", ["dairy", "milk", "yogurt", "cheese"]),
    ("fast_food", ["fast food", "burger", "pizza", "fries"]),
    ("protein", ["protein", "chicken", "beef", "fish", "egg", "tuna"]),
    ("snack", ["snack", "chips", "cracker", "nuts"]),
]


def normalize_search_text(value):
    if value is None:
        return ""
    text = unicodedata.normalize("NFKC", str(value)).casefold()
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")
    text = re.sub(r"[^\w\s]+", " ", text, flags=re.UNICODE)
    return re.sub(r"\s+", " ", text).strip()


def seed_categories_aliases_and_search_data(apps, schema_editor):
    FoodCategory = apps.get_model("core", "FoodCategory")
    FoodItem = apps.get_model("core", "FoodItem")
    FoodItemAlias = apps.get_model("core", "FoodItemAlias")

    categories = {}
    for code, name, sort_order in CATEGORY_SEEDS:
        category, _ = FoodCategory.objects.update_or_create(
            code=code,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )
        categories[code] = category

    uncategorized = categories["uncategorized"]

    for item in FoodItem.objects.all():
        normalized_name = normalize_search_text(item.name)
        normalized_brand_name = normalize_search_text(item.brand_name)
        text_for_category = normalize_search_text(
            " ".join(
                part
                for part in [item.name, item.category, item.brand_name]
                if part
            )
        )
        category = _resolve_category(item, text_for_category, categories, uncategorized)

        item.normalized_name = normalized_name
        item.normalized_brand_name = normalized_brand_name
        if item.primary_category_id is None:
            item.primary_category = category
        item.save(
            update_fields=[
                "normalized_name",
                "normalized_brand_name",
                "primary_category",
            ]
        )

        _upsert_alias(
            FoodItemAlias,
            item=item,
            alias=item.name,
            alias_type="common_name",
            is_primary=True,
            sort_order=0,
        )
        if item.brand_name:
            _upsert_alias(
                FoodItemAlias,
                item=item,
                alias=item.brand_name,
                alias_type="brand_name",
                is_primary=False,
                sort_order=10,
            )
        aliases = item.aliases if isinstance(item.aliases, list) else []
        for index, alias in enumerate(aliases, start=20):
            _upsert_alias(
                FoodItemAlias,
                item=item,
                alias=alias,
                alias_type="common_name",
                is_primary=False,
                sort_order=index,
            )


def _resolve_category(item, normalized_text, categories, fallback):
    legacy_category = normalize_search_text(item.category).replace(" ", "_")
    if legacy_category in categories:
        return categories[legacy_category]
    for code, keywords in CATEGORY_KEYWORDS:
        if any(normalize_search_text(keyword) in normalized_text for keyword in keywords):
            return categories[code]
    return fallback


def _upsert_alias(FoodItemAlias, *, item, alias, alias_type, is_primary, sort_order):
    normalized_alias = normalize_search_text(alias)
    if not normalized_alias:
        return
    FoodItemAlias.objects.update_or_create(
        food_item=item,
        normalized_alias=normalized_alias,
        alias_type=alias_type,
        defaults={
            "alias": str(alias).strip(),
            "is_primary": is_primary,
            "sort_order": sort_order,
        },
    )


def create_pg_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    try:
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS core_fooditem_norm_name_trgm_idx "
            "ON core_fooditem USING gin (normalized_name gin_trgm_ops)"
        )
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS core_fooditem_name_trgm_idx "
            "ON core_fooditem USING gin (name gin_trgm_ops)"
        )
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS core_foodalias_norm_trgm_idx "
            "ON core_fooditemalias USING gin (normalized_alias gin_trgm_ops)"
        )
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS core_foodalias_alias_trgm_idx "
            "ON core_fooditemalias USING gin (alias gin_trgm_ops)"
        )
    except Exception:
        pass


def drop_pg_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for index_name in [
        "core_fooditem_norm_name_trgm_idx",
        "core_fooditem_name_trgm_idx",
        "core_foodalias_norm_trgm_idx",
        "core_foodalias_alias_trgm_idx",
    ]:
        schema_editor.execute(f"DROP INDEX IF EXISTS {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_nutrient_fooditem_aliases_fooditem_contains_caffeine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=120)),
                ('normalized_alias', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('alias_type', models.CharField(choices=[('common_name', 'Common name'), ('brand_name', 'Brand name'), ('arabic_name', 'Arabic name'), ('english_name', 'English name'), ('misspelling', 'Misspelling'), ('short_name', 'Short name')], default='common_name', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('food_item__name', 'sort_order', 'alias'),
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='normalized_brand_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='search_priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='contains_caffeine',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_hydration_trackable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_type',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('drink', 'Drink')], db_index=True, default='food', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=20),
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.foodcategory')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.foodcategory'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['item_type', 'is_active'], name='fooditem_type_active_idx'),
        ),
        migrations.AddField(
            model_name='fooditemalias',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_records', to='core.fooditem'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['parent', 'sort_order'], name='foodcat_parent_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditemalias',
            index=models.Index(fields=['food_item', 'is_primary'], name='foodalias_item_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='fooditemalias',
            constraint=models.UniqueConstraint(fields=('food_item', 'normalized_alias', 'alias_type'), name='unique_fooditem_alias_type'),
        ),
        migrations.RunPython(
            seed_categories_aliases_and_search_data,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(create_pg_trigram_indexes, drop_pg_trigram_indexes),
    ]
