# Generated by Django 5.2.10 on 2026-04-17 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fooditemalias_fooditem_normalized_brand_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedTrackerConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('activity', 'Activity'), ('steps', 'Steps'), ('sleep', 'Sleep'), ('medication', 'Medication'), ('monitoring', 'Monitoring'), ('habit', 'Habit'), ('micronutrient', 'Micronutrient')], db_index=True, max_length=30)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('metric_key', models.CharField(db_index=True, max_length=100)),
                ('rule_type', models.CharField(choices=[('target', 'Target'), ('min', 'Minimum'), ('max', 'Maximum'), ('warn', 'Warning'), ('avoid', 'Avoid'), ('range', 'Range')], default='target', max_length=30)),
                ('evaluation_mode', models.CharField(blank=True, default='daily_total', max_length=60)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('warning_value', models.FloatField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('is_blocking', models.BooleanField(default=False)),
                ('is_scored', models.BooleanField(default=True)),
                ('source_type', models.CharField(choices=[('physician_override', 'Physician override'), ('safety_critical_condition_rule', 'Safety critical condition rule'), ('dynamic_condition_state', 'Dynamic condition state'), ('condition_nutrient_rule', 'Condition nutrient rule'), ('user_custom_target', 'User custom target'), ('profile_derived_default', 'Profile derived default'), ('general_recommendation', 'General recommendation')], db_index=True, default='general_recommendation', max_length=50)),
                ('reason_summary', models.CharField(blank=True, max_length=255)),
                ('explanation_payload', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('version_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_constraints', to='core.usercondition')),
                ('source_nutrient_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_constraints', to='core.conditionnutrientrule')),
                ('source_restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_constraints', to='core.healthrestriction')),
                ('source_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_constraints', to='core.healthtarget')),
                ('source_user_nutrient_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_constraints', to='core.usernutrienttarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_tracker_constraints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tracker_type', 'metric_key', '-priority', '-computed_at'),
            },
        ),
        migrations.CreateModel(
            name='ConstraintSourceTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(max_length=120)),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('contribution_type', models.CharField(choices=[('selected', 'Selected'), ('superseded', 'Superseded'), ('supporting', 'Supporting')], default='selected', max_length=30)),
                ('priority_score', models.PositiveSmallIntegerField(default=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_traces', to='core.resolvedtrackerconstraint')),
            ],
            options={
                'ordering': ('resolved_constraint_id', 'contribution_type', 'source_model'),
            },
        ),
        migrations.CreateModel(
            name='ConstraintResolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('user_profile', 'User profile'), ('user_condition', 'User condition'), ('health_target', 'Health target'), ('user_nutrient_target', 'User nutrient target'), ('health_indicator_record', 'Health indicator record'), ('condition_rule_catalog', 'Condition rule catalog'), ('medication_plan', 'Medication plan'), ('nightly_safety_recompute', 'Nightly safety recompute')], default='manual', max_length=60)),
                ('trigger_reference', models.CharField(blank=True, max_length=255)),
                ('input_signature', models.CharField(db_index=True, max_length=64)),
                ('run_status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=20)),
                ('total_constraints_generated', models.PositiveIntegerField(default=0)),
                ('total_constraints_superseded', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_resolution_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['user', 'run_status', 'started_at'], name='crr_user_status_started_idx'), models.Index(fields=['user', 'trigger_type', 'started_at'], name='crr_user_trigger_started_idx'), models.Index(fields=['user', 'input_signature', 'run_status'], name='crr_user_signature_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resolvedtrackerconstraint',
            index=models.Index(fields=['user', 'tracker_type', 'status'], name='rtc_user_tracker_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resolvedtrackerconstraint',
            index=models.Index(fields=['user', 'category', 'status'], name='rtc_user_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resolvedtrackerconstraint',
            index=models.Index(fields=['user', 'metric_key', 'status'], name='rtc_user_metric_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resolvedtrackerconstraint',
            index=models.Index(fields=['user', 'effective_to', 'status'], name='rtc_user_to_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resolvedtrackerconstraint',
            index=models.Index(fields=['user', 'source_type', 'status'], name='rtc_user_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='constraintsourcetrace',
            index=models.Index(fields=['resolved_constraint', 'contribution_type'], name='cst_constraint_type_idx'),
        ),
        migrations.AddIndex(
            model_name='constraintsourcetrace',
            index=models.Index(fields=['source_model', 'source_object_id'], name='cst_source_object_idx'),
        ),
    ]
