# Generated by Django 5.2.10 on 2026-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_health_state_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='avg_speed_kmh',
            field=models.FloatField(default=0.0, help_text='Average speed'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='distance_km',
            field=models.FloatField(default=0.0, help_text='Distance covered'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='met_value',
            field=models.FloatField(help_text='MET value'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='quality',
            field=models.CharField(choices=[('Deep', 'Deep'), ('Light', 'Light'), ('Interrupted', 'Interrupted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='amount_liter',
            field=models.FloatField(help_text='Quantity in liters'),
        ),
    ]
