# Generated by Django 5.2.10 on 2026-05-07 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sleep_coach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnhealthyHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(choices=[('smoking', 'Smoking'), ('caffeine', 'Caffeine'), ('fast_food', 'Fast food')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('goal_type', models.CharField(choices=[('reduce', 'Reduce'), ('quit', 'Quit')], default='reduce', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], db_index=True, default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unhealthy_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('habit_type', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UnhealthyHabitBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_frequency', models.FloatField(default=0)),
                ('initial_quantity', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('common_trigger', models.CharField(blank=True, default='', max_length=80)),
                ('common_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='core.unhealthyhabit')),
            ],
        ),
        migrations.CreateModel(
            name='UnhealthyHabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('log_date', models.DateField(db_index=True)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('trigger', models.CharField(blank=True, default='', max_length=80)),
                ('mood', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_relapse', models.BooleanField(default=False)),
                ('is_within_limit', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration')], default='manual', max_length=20)),
                ('sync_to_tracker', models.BooleanField(default=False)),
                ('caffeine_mg', models.FloatField(default=0)),
                ('calories_kcal', models.FloatField(default=0)),
                ('food_name', models.CharField(blank=True, default='', max_length=160)),
                ('healthy_replacement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.unhealthyhabit')),
                ('linked_meal_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unhealthy_habit_logs', to='core.meallog')),
                ('linked_water_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unhealthy_habit_logs', to='core.waterlog')),
            ],
            options={
                'ordering': ('-logged_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UnhealthyHabitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.FloatField(blank=True, null=True)),
                ('weekly_limit', models.FloatField(blank=True, null=True)),
                ('target_quantity', models.FloatField(blank=True, null=True)),
                ('reduction_percentage', models.FloatField(default=0)),
                ('cutoff_time', models.TimeField(blank=True, null=True)),
                ('plan_stage', models.CharField(blank=True, default='', max_length=80)),
                ('healthy_replacement_required', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='core.unhealthyhabit')),
            ],
        ),
        migrations.CreateModel(
            name='UnhealthyHabitPointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('logged', 'Logged'), ('within_limit', 'Within limit'), ('improvement', 'Improvement'), ('healthy_replacement', 'Healthy replacement')], max_length=40)),
                ('event_date', models.DateField(db_index=True)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to='core.unhealthyhabit')),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to='core.unhealthyhabitlog')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UnhealthyHabitReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.TimeField()),
                ('message', models.CharField(blank=True, default='', max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.unhealthyhabit')),
            ],
            options={
                'ordering': ('time_of_day', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='unhealthyhabit',
            index=models.Index(fields=['user', 'habit_type', 'status'], name='unhealthy_habit_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='unhealthyhabitlog',
            index=models.Index(fields=['habit', 'log_date'], name='unhealthy_log_habit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='unhealthyhabitlog',
            index=models.Index(fields=['habit', 'is_relapse'], name='unhealthy_log_relapse_idx'),
        ),
        migrations.AddConstraint(
            model_name='unhealthyhabitpointevent',
            constraint=models.UniqueConstraint(fields=('habit', 'event_type', 'event_date', 'log'), name='unique_unhealthy_point_event'),
        ),
    ]
