# Generated by Django 5.2.10 on 2026-07-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_activity_session_live_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthstatedelta',
            name='notification_candidates',
        ),
        migrations.DeleteModel(
            name='NotificationDispatchRecord',
        ),
    ]
