# Generated by Django 5.2.10 on 2026-07-26 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_steplog_source_breakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='meallog',
            name='is_fast_food',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='meallog',
            name='origin_domain',
            field=models.CharField(blank=True, db_index=True, default='nutrition', max_length=24),
        ),
        migrations.AddField(
            model_name='meallog',
            name='origin_record_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='meallog',
            name='projection_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meallog',
            name='quality_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='meallog',
            name='reward_owner_domain',
            field=models.CharField(blank=True, default='nutrition', max_length=24),
        ),
        migrations.AddField(
            model_name='meallog',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='meallog',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='direct_user_entry', max_length=32),
        ),
        migrations.AddField(
            model_name='unhealthyhabit',
            name='setup_idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='is_abstinence_checkin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='meal_type',
            field=models.CharField(blank=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='origin_domain',
            field=models.CharField(choices=[('habits', 'Habits'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration')], db_index=True, default='habits', max_length=24),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='origin_record_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='projection_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='reward_owner_domain',
            field=models.CharField(blank=True, default='habits', max_length=24),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='unhealthyhabitlog',
            name='source_type',
            field=models.CharField(choices=[('direct_user_entry', 'Direct user entry'), ('habit_projection', 'Habit projection'), ('tracker_projection', 'Tracker projection'), ('imported', 'Imported')], db_index=True, default='direct_user_entry', max_length=32),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='caffeine_mg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='origin_domain',
            field=models.CharField(blank=True, db_index=True, default='hydration', max_length=24),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='origin_record_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='projection_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='reward_owner_domain',
            field=models.CharField(blank=True, default='hydration', max_length=24),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='direct_user_entry', max_length=32),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('barcode', 'Barcode'), ('favorite', 'Favorite'), ('ai', 'AI'), ('habit_sync', 'Habit sync')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='unhealthyhabitlog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('habit_sync', 'Habit sync'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'source_type', 'source_ref'], name='meal_log_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['origin_domain', 'origin_record_id'], name='meal_log_origin_idx'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'is_fast_food', 'date'], name='meal_log_fast_food_idx'),
        ),
        migrations.AddIndex(
            model_name='unhealthyhabit',
            index=models.Index(fields=['user', 'setup_idempotency_key'], name='unhealthy_habit_setup_key_idx'),
        ),
        migrations.AddIndex(
            model_name='unhealthyhabitlog',
            index=models.Index(fields=['habit', 'source_type', 'source_ref'], name='unhealthy_log_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='unhealthyhabitlog',
            index=models.Index(fields=['origin_domain', 'origin_record_id'], name='unhealthy_log_origin_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlog',
            index=models.Index(fields=['user', 'source_type', 'source_ref'], name='water_log_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlog',
            index=models.Index(fields=['origin_domain', 'origin_record_id'], name='water_log_origin_idx'),
        ),
        migrations.AddConstraint(
            model_name='meallog',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('user', 'source_type', 'source_ref'), name='unique_meal_log_projection_ref'),
        ),
        migrations.AddConstraint(
            model_name='unhealthyhabit',
            constraint=models.UniqueConstraint(condition=models.Q(('setup_idempotency_key', ''), _negated=True), fields=('user', 'setup_idempotency_key'), name='unique_unhealthy_habit_setup_key'),
        ),
        migrations.AddConstraint(
            model_name='unhealthyhabitlog',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('habit', 'source_type', 'source_ref'), name='unique_unhealthy_log_projection_ref'),
        ),
        migrations.AddConstraint(
            model_name='waterlog',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('user', 'source_type', 'source_ref'), name='unique_water_log_projection_ref'),
        ),
    ]
