# Generated by Django 5.2.10 on 2026-08-03 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_waterlog_consumed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLogComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name_snapshot', models.CharField(max_length=160)),
                ('quantity_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_unit', models.CharField(default='g', max_length=20)),
                ('resolved_grams', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('resolved_milliliters', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('nutrition_snapshot', models.JSONField(default=dict)),
                ('source_label', models.CharField(blank=True, default='', max_length=160)),
                ('is_user_confirmed', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='meallog',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='meallog',
            name='finalization_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='meallog',
            name='is_composite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='food',
            field=models.ForeignKey(blank=True, help_text='Primary food for legacy single-component meal logs.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fooditem'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'consumed_at'], name='meal_log_consumed_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='meallog',
            constraint=models.UniqueConstraint(condition=models.Q(('finalization_key', ''), _negated=True), fields=('user', 'finalization_key'), name='unique_meal_finalization_key'),
        ),
        migrations.AddField(
            model_name='meallogcomponent',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_log_components', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='meallogcomponent',
            name='meal_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.meallog'),
        ),
        migrations.AddIndex(
            model_name='meallogcomponent',
            index=models.Index(fields=['meal_log', 'sort_order'], name='meal_component_order_idx'),
        ),
        migrations.AddIndex(
            model_name='meallogcomponent',
            index=models.Index(fields=['food_item'], name='meal_component_food_idx'),
        ),
        migrations.AddConstraint(
            model_name='meallogcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_value__gt', 0)), name='meal_component_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='meallogcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_grams__gt', 0), ('resolved_milliliters__gt', 0), _connector='OR'), name='meal_component_has_resolved_amount'),
        ),
        migrations.AddConstraint(
            model_name='meallogcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='meal_component_confidence_range'),
        ),
    ]
