# Generated by Django 5.2.10 on 2026-08-03 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_normalize_nutrition_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True), models.Q(('normalized_name', ''), _negated=True)), fields=('normalized_name',), name='unique_global_food_normalized_name'),
        ),
        migrations.AddConstraint(
            model_name='nutritionfacts',
            constraint=models.CheckConstraint(condition=models.Q(('basis_value__gt', 0), ('basis_amount__gt', 0), ('serving_size__gt', 0)), name='nutrition_facts_positive_basis'),
        ),
        migrations.AddConstraint(
            model_name='nutritionfacts',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('basis_type', 'per_100g'), ('basis_unit', 'g')), models.Q(('basis_type', 'per_100ml'), ('basis_unit', 'ml')), models.Q(('basis_type', 'per_serving'), ('basis_unit', 'serving')), _connector='OR'), name='nutrition_facts_basis_consistent'),
        ),
        migrations.AddConstraint(
            model_name='nutritionfacts',
            constraint=models.CheckConstraint(condition=models.Q(('calories_kcal__gte', 0), ('protein_g__gte', 0), ('carbohydrates_g__gte', 0), ('sugars_g__gte', 0), ('fiber_g__gte', 0), ('fat_g__gte', 0), ('sodium_mg__gte', 0)), name='nutrition_facts_core_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='nutritionfacts',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='nutrition_facts_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='nutritionservingoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('food_item',), name='unique_default_serving_per_food'),
        ),
        migrations.AddConstraint(
            model_name='nutritionservingoption',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='nutrition_serving_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='nutritionservingoption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grams_equivalent__isnull', True), ('grams_equivalent__gte', 0), _connector='OR'), models.Q(('milliliters_equivalent__isnull', True), ('milliliters_equivalent__gte', 0), _connector='OR')), name='nutrition_serving_equivalents_nonnegative'),
        ),
    ]
