# Generated by Django 5.2.10 on 2026-05-12 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('icon', models.CharField(blank=True, default='', max_length=48)),
                ('condition_type', models.CharField(choices=[('streak', 'Streak'), ('counter', 'Counter')], default='streak', max_length=24)),
                ('condition_key', models.CharField(db_index=True, max_length=64)),
                ('required_value', models.IntegerField(default=1)),
                ('points_bonus', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='userscore',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_date', models.DateField(db_index=True)),
                ('mission_type', models.CharField(db_index=True, max_length=48)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('target_value', models.FloatField(default=0)),
                ('current_value', models.FloatField(default=0)),
                ('points_reward', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed')], db_index=True, default='pending', max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=220)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('mission_type', 'id'),
                'indexes': [models.Index(fields=['user', 'mission_date'], name='daily_mission_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'mission_date', 'mission_type'), name='unique_daily_mission_per_type')],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('system', 'System'), ('hydration', 'Hydration'), ('nutrition', 'Nutrition'), ('activity', 'Activity'), ('steps', 'Steps'), ('sleep', 'Sleep'), ('medication', 'Medication'), ('chronic', 'Chronic'), ('habits', 'Habits'), ('motivation', 'Motivation')], default='system', max_length=24)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('rule_code', models.CharField(max_length=64)),
                ('points', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('event_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(db_index=True, max_length=191, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'event_date'], name='points_tx_user_date_idx'), models.Index(fields=['user', 'source_type'], name='points_tx_user_source_idx'), models.Index(fields=['user', 'rule_code'], name='points_tx_user_rule_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_value', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('earned', 'Earned')], db_index=True, default='in_progress', max_length=24)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('badge_id', 'id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_badge')],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(db_index=True, max_length=48)),
                ('current_count', models.IntegerField(default=0)),
                ('longest_count', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('streak_type', 'id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'streak_type'), name='unique_user_streak_type')],
            },
        ),
    ]
