# Generated by Django 5.2.10 on 2026-07-03 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge_userscore_current_streak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='event_type',
            field=models.CharField(choices=[('award', 'Award'), ('bonus', 'Bonus'), ('correction', 'Correction'), ('reversal', 'Reversal')], db_index=True, default='award', max_length=20),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_transactions', to='gamification.pointstransaction'),
        ),
        migrations.AlterField(
            model_name='dailymission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_applicable', 'Not applicable')], db_index=True, default='pending', max_length=24),
        ),
        migrations.CreateModel(
            name='DailyMotivationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateField(db_index=True)),
                ('hydration_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_applicable', 'Not applicable')], default='pending', max_length=24)),
                ('nutrition_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_applicable', 'Not applicable')], default='pending', max_length=24)),
                ('activity_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_applicable', 'Not applicable')], default='pending', max_length=24)),
                ('sleep_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_applicable', 'Not applicable')], default='pending', max_length=24)),
                ('medication_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=24)),
                ('habits_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=24)),
                ('completed_missions_count', models.IntegerField(default=0)),
                ('not_applicable_missions_count', models.IntegerField(default=0)),
                ('total_daily_points', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_motivation_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-state_date', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'state_date'), name='unique_daily_motivation_state')],
            },
        ),
        migrations.CreateModel(
            name='DailyStepPointsAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField(db_index=True)),
                ('highest_threshold_awarded', models.IntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('goal_bonus_awarded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_step_point_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-award_date', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'award_date'), name='unique_daily_step_points_award')],
            },
        ),
    ]
