# Generated by Django 5.2.10 on 2026-07-07 19:56

import django.db.models.deletion
import django.utils.timezone
import notification_hub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(db_index=True, max_length=191)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('windows', 'Windows')], default='android', max_length=24)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('locale', models.CharField(blank=True, default='', max_length=32)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('notifications_authorized', models.BooleanField(default=False)),
                ('exact_alarm_authorized', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_primary', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(db_index=True, default=notification_hub.models._plan_id, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('rule', 'Rule'), ('intent', 'Intent'), ('in_app', 'In-app')], default='rule', max_length=16)),
                ('category', models.CharField(choices=[('health_critical', 'Health critical'), ('routine', 'Routine'), ('motivation', 'Motivation'), ('celebration', 'Celebration'), ('system', 'System')], default='routine', max_length=24)),
                ('type', models.CharField(db_index=True, max_length=80)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, default='', max_length=240)),
                ('route', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('schedule_spec', models.JSONField(blank=True, default=dict)),
                ('deliver_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('sound_profile', models.CharField(blank=True, default='', max_length=32)),
                ('exact_required', models.BooleanField(default=False)),
                ('foreground_behavior', models.CharField(blank=True, default='', max_length=32)),
                ('dedupe_key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('suppressed', 'Suppressed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='planned', max_length=16)),
                ('source_domain', models.CharField(blank=True, default='', max_length=80)),
                ('source_ref', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='notification_hub.notificationdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-priority', 'plan_id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationPlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('scheduled_local', 'Scheduled locally'), ('foreground_suppressed', 'Foreground suppressed'), ('opened', 'Opened'), ('dismissed', 'Dismissed'), ('delivered', 'Delivered'), ('schedule_failed', 'Schedule failed'), ('cancelled_local', 'Cancelled locally')], db_index=True, max_length=32)),
                ('event_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_events', to='notification_hub.notificationdevice')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notification_hub.notificationplan')),
            ],
            options={
                'ordering': ('-event_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_routine_reminders', models.BooleanField(default=True)),
                ('enable_motivation_reminders', models.BooleanField(default=True)),
                ('enable_health_alerts', models.BooleanField(default=True)),
                ('enable_medication_reminders', models.BooleanField(default=True)),
                ('enable_sleep_reminders', models.BooleanField(default=False)),
                ('enable_water_reminders', models.BooleanField(default=True)),
                ('enable_meal_reminders', models.BooleanField(default=False)),
                ('enable_activity_reminders', models.BooleanField(default=True)),
                ('enable_step_reminders', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('motivation_max_per_day', models.PositiveSmallIntegerField(default=2)),
                ('motivation_type_cooldown_hours', models.PositiveSmallIntegerField(default=6)),
                ('critical_bypass_quiet_hours', models.BooleanField(default=True)),
                ('breakfast_reminder_time', models.TimeField(blank=True, null=True)),
                ('lunch_reminder_time', models.TimeField(blank=True, null=True)),
                ('dinner_reminder_time', models.TimeField(blank=True, null=True)),
                ('steps_reminder_time', models.TimeField(blank=True, null=True)),
                ('water_reminder_start_time', models.TimeField(blank=True, null=True)),
                ('water_reminder_end_time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.AddIndex(
            model_name='notificationdevice',
            index=models.Index(fields=['user', 'is_primary', 'updated_at'], name='nh_device_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdevice',
            constraint=models.UniqueConstraint(fields=('user', 'installation_id'), name='unique_notification_device_installation'),
        ),
        migrations.AddIndex(
            model_name='notificationplan',
            index=models.Index(fields=['device', 'status', 'updated_at'], name='nh_plan_device_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationplan',
            index=models.Index(fields=['user', 'category', 'status'], name='nh_plan_user_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationplan',
            constraint=models.UniqueConstraint(fields=('device', 'dedupe_key'), name='unique_notification_plan_per_device_dedupe'),
        ),
        migrations.AddIndex(
            model_name='notificationplanevent',
            index=models.Index(fields=['device', 'event_type', 'event_at'], name='nh_event_device_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationplanevent',
            index=models.Index(fields=['plan', 'event_type', 'event_at'], name='nh_event_plan_type_idx'),
        ),
    ]
