# Generated by Django 5.2.10 on 2026-07-26 08:46

from django.db import migrations, models


def copy_routine_preference_to_habits(apps, schema_editor):
    profile = apps.get_model("notification_hub", "NotificationPreferenceProfile")
    for row in profile.objects.all().only("id", "enable_routine_reminders"):
        row.enable_habit_reminders = row.enable_routine_reminders
        row.save(update_fields=["enable_habit_reminders"])


def restore_habit_preference_default(apps, schema_editor):
    profile = apps.get_model("notification_hub", "NotificationPreferenceProfile")
    profile.objects.update(enable_habit_reminders=True)


class Migration(migrations.Migration):

    dependencies = [
        ('notification_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferenceprofile',
            name='enable_habit_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            copy_routine_preference_to_habits,
            reverse_code=restore_habit_preference_default,
        ),
    ]
