# Generated by Django 5.2.10 on 2026-08-03 01:11

import ai_meals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0038_nutrition_catalog_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=ai_meals.models.analysis_image_upload_path)),
                ('image_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('review', 'Review'), ('needs_input', 'Needs input'), ('ready_to_finalize', 'Ready to finalize'), ('failed', 'Failed'), ('finalized', 'Finalized'), ('expired', 'Expired')], db_index=True, default='uploaded', max_length=24)),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_status', models.CharField(blank=True, default='', max_length=40)),
                ('decision_code', models.CharField(blank=True, default='', max_length=80)),
                ('finalize_allowed', models.BooleanField(default=False)),
                ('required_user_inputs', models.JSONField(blank=True, default=list)),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('model_versions', models.JSONField(blank=True, default=dict)),
                ('selected_dish_id', models.CharField(blank=True, default='', max_length=120)),
                ('selected_dish_label', models.CharField(blank=True, default='', max_length=160)),
                ('estimated_weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('finalization_key', models.CharField(blank=True, default='', max_length=120)),
                ('failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_meal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_session', to='core.meallog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MealAnalysisComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_label', models.CharField(max_length=160)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('suggested_percentage', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('suggested_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_included', models.BooleanField(default=True)),
                ('is_user_confirmed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('mapped_food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_components', to='core.fooditem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='ai_meals.mealanalysissession')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MealAnalysisCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dish', 'Dish'), ('ingredient', 'Ingredient')], max_length=20)),
                ('provider_id', models.CharField(blank=True, default='', max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('display_name_ar', models.CharField(blank=True, default='', max_length=160)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('mapped_food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_candidates', to='core.fooditem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ai_meals.mealanalysissession')),
            ],
            options={
                'ordering': ('kind', 'rank', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AIIngredientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('provider_label', models.CharField(max_length=160)),
                ('normalized_label', models.CharField(db_index=True, max_length=180)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('mapping_confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_ingredient_mappings', to='core.fooditem')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ai_ingredient_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('normalized_label', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('normalized_label',), name='unique_active_ai_ingredient_label')],
            },
        ),
        migrations.AddIndex(
            model_name='mealanalysissession',
            index=models.Index(fields=['user', 'status', 'created_at'], name='ai_meal_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealanalysiscomponent',
            constraint=models.UniqueConstraint(fields=('session', 'sort_order'), name='unique_ai_component_order'),
        ),
        migrations.AddConstraint(
            model_name='mealanalysiscomponent',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_grams__isnull', True), ('confirmed_grams__gt', 0), _connector='OR'), name='ai_component_confirmed_grams_positive'),
        ),
        migrations.AddConstraint(
            model_name='mealanalysiscandidate',
            constraint=models.UniqueConstraint(fields=('session', 'kind', 'rank'), name='unique_ai_candidate_rank'),
        ),
    ]
