# Generated by Django 5.2.10 on 2026-08-03 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_meals', '0002_mealanalysissession_analysis_key'),
        ('core', '0040_favorite_food'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiingredientmapping',
            name='unique_active_ai_ingredient_label',
        ),
        migrations.AddField(
            model_name='aiingredientmapping',
            name='provider',
            field=models.CharField(db_index=True, default='vitamate_ai', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='aiingredientmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('provider_id', ''), _negated=True)), fields=('provider', 'provider_id'), name='unique_active_ai_provider_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='aiingredientmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('provider_id', '')), fields=('provider', 'normalized_label'), name='unique_active_ai_provider_label'),
        ),
    ]
